### ISSUE TITLE
Constant CPU usage

### ISSUE THREAD

**Issue by Altycoder** [calibrain/calibre-web-automated-book-downloader#114]
Spin up new container, and inspect docker stats via over a period of 5-10 min:

`docker stats -a`

CPU usage for this container is sitting at an almost constant 15% even though there is nothing being searched or downloaded.  This is on an Arch Linux LTS OS with 32GB RAM and an i5-13500 CPU.

Docker compose:

```
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: calibre-web-automated-book-downloader
    environment:
      FLASK_PORT: 8095
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      UID: ${PUID}
      GID: ${PGID}
      TZ: ${TZ}
      UMASK: 002
    networks:
      - media
    ports:
      - 8095:8095
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIR}/calibre-web-automated/ingest:${INGEST_DIR:-/cwa-book-ingest}
```

container logs via portainer:

```
[cwa-auto-zipper] Fixed_Originals - no files found to zip.
[cwa-auto-zipper] No files from 2025-03-28 found to be zipped. Exiting now...
[cwa-auto-zipper] Next run in 86340 seconds.
[cwa-auto-zipper] Successfully initiated, processing new files from 2025-03-29...
[cwa-auto-zipper] Converted - no files found to zip.
[cwa-auto-zipper] Failed - no files found to zip.
[cwa-auto-zipper] Imported - no files found to zip.
[cwa-auto-zipper] Fixed_Originals - no files found to zip.
[cwa-auto-zipper] No files from 2025-03-29 found to be zipped. Exiting now...
[cwa-auto-zipper] Next run in 82740 seconds.
[migrations] started
[migrations] no migrations found
usermod: no changes
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
         ,gggg,                                                                    ,ggg,      gg      ,gg                              
       ,88"""Y8b,             ,dPYb,       ,dPYb,                                 dP""Y8a     88     ,8P          ,dPYb,               
      d8"     `Y8             IP'`Yb       IP'`Yb                                 Yb, `88     88     d8'          IP'`Yb               
     d8'   8b  d8             I8  8I  gg   I8  8I                                  `"  88     88     88           I8  8I               
    ,8I    "Y88P'             I8  8'  ""   I8  8'                                      88     88     88           I8  8'               
    I8'             ,gggg,gg  I8 dP   gg   I8 dP        ,gggggg,   ,ggg,   aaaaaaaa    88     88     88   ,ggg,   I8 dP                
    d8             dP"  "Y8I  I8dP    88   I8dP   88gg  dP""""8I  i8" "8i  """"""""    88     88     88  i8" "8i  I8dP   88gg          
    Y8,           i8'    ,8I  I8P     88   I8P    8I   ,8'    8I  I8, ,8I              Y8    ,88,    8P  I8, ,8I  I8P    8I            
    `Yba,,_____, ,d8,   ,d8b,,d8b,_ _,88,_,d8b,  ,8I  ,dP     Y8, `YbadP'               Yb,,d8""8b,,dP   `YbadP' ,d8b,  ,8I            
      `"Y8888888 P"Y8888P"`Y88P'"Y888P""Y88P'"Y88P"'  8P      `Y8888P"Y888               "88"    "88"   888P"Y8888P'"Y88P"'            
                         █████╗ ██╗   ██╗████████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗███████╗██████╗ 
                        ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
                        ███████║██║   ██║   ██║   ██║   ██║██╔████╔██║███████║   ██║   █████╗  ██║  ██║
                        ██╔══██║██║   ██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██╔══╝  ██║  ██║
                        ██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║   ███████╗██████╔╝
                        ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝ 
                             ~~~ Based on images from linuxserver.io & Calibre-Web by janeczku ~~~
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[cwa-init] Checking for leftover lock files from previous instance...
[cwa-init] No leftover lock files to remove. Ending service...
[cwa-init] Checking for an existing app.db in /config...
[cwa-init] Existing app.db found!
[cwa-init] Setting binary paths in '/config/app.db' to the correct ones...
[universal-calibre-setup] Skipping setup, Calibre already installed. Exiting now...
[cwa-init] Successfully set binary paths in '/config/app.db'!
[cwa-init] CWA-init complete! Service exiting now...
[cwa-init] Recursively setting ownership of everything in /config, /calibre-library, /app/calibre-web-automated to abc:abc...
[cwa-init] Successfully set permissions for '/config'!
[cwa-init] Successfully set permissions for '/calibre-library'!
[cwa-init] Successfully set permissions for '/app/calibre-web-automated'!
[cwa-auto-zipper] Starting CWA-Auto-Zipper service...
[cwa-auto-zipper] Matching internal localtime & timezone with the one provided...
[cwa-auto-zipper] Zoneinfo for Europe/London found. Setting /etc/localtime and /etc/timezone to match...
[cwa-auto-zipper] Timezone & Localtime successfully set to Europe/London. Initiating Auto-Zipper ...
[cwa-auto-zipper] Next run in 49629 seconds.
[cwa-auto-library]: Multiple metadata.db files found in library directory:
    - /calibre-library/metadata.db | Size: 10186752
    - /calibre-library/metadata.db-mj0F5A9A962 | Size: 81
[cwa-auto-library]: Automatically mounting the largest database using the following db file - /calibre-library/metadata.db ...
[cwa-auto-library]: If this is unwanted, please ensure only 1 metadata.db file / only your desired Calibre Database exists in '/calibre-library', then restart the container
[cwa-auto-library] Updating dirs.json with new library location...
[cwa-auto-library]: Updating Settings Database with library location...
[cwa-auto-library] Library location successfully set to: /calibre-library
========== STARTING METADATA CHANGE DETECTOR ===========
========== STARTING CWA-INGEST SERVICE ==========
[metadata-change-detector] Watching folder: /app/calibre-web-automated/metadata_change_logs
[cwa-ingest-service] Watching folder: /cwa-book-ingest
Setting up watches.
Watches established.
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
[ls.io-init] done.
[cwa-auto-zipper] Successfully initiated, processing new files from 2025-03-30...
[cwa-auto-zipper] Converted - no files found to zip.
[cwa-auto-zipper] Failed - no files found to zip.
[cwa-auto-zipper] Imported - no files found to zip.
[cwa-auto-zipper] Fixed_Originals - no files found to zip.
[cwa-auto-zipper] No files from 2025-03-30 found to be zipped. Exiting now...
[cwa-auto-zipper] Next run in 86340 seconds.

```

**Comment by Altycoder** [comment]
Container has been running afresh for 10-15 min.  Docker stats:

```
CONTAINER ID   NAME                                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
b2b63f13b44b   calibre-web-automated-book-downloader   15.51%    486.2MiB / 31.09GiB   1.53%     10.2MB / 519kB    308MB / 76.6MB    132
```

**Comment by Altycoder** [comment]
Thanks. I think there must be an associated memory leak as well as my swap usage has been creeping up to 14% and with this container shut down whilst you fix, my swap usage is staying at zero.

**Comment by zewelor** [comment]
Maybe instead of running chrome this will be enough https://github.com/lexiforest/curl_cffi

**Comment by Altycoder** [comment]
Hi, I'm away for the next week or so, so won't be able to try anything out I'm afraid

**Comment by calibrain** [comment]
The problem with all these non browser solution is the "clicking" part
AA is always set to be in "Attack Mode", with the highest level of security.Meaning a "click" action MUST be triggered to give you access to the website. Most of these solution bypass the implicit cloudflare turnstile, which fingerprints your browser for non human activity (and that can be bypassed without an actual browser). But to click on the verify you are human thing,

![Image](https://github.com/user-attachments/assets/fb788350-faee-47e6-8ac9-48e38dedd94b)

There is too much logic to bypass it statically, and right now the best approach is literally using a GUI to mimic a mouse moving and clicking on the button.
I am working on a such custom solution, but it takes time and lots of testing.

**Comment by zewelor** [comment]
I know there is also this: https://github.com/FlareSolverr/FlareSolverr. But I think they didn't implement clicking verify checkbox

**Comment by calibrain** [comment]
At some point I was using it, but it had too many issues, also did not support proxy, and no logging for failures etc.
I moved to https://github.com/g1879/DrissionPage but its in Chinese (I don't speak Chinese) and really hard to debug too
But it works relatively well and its what we are using now, but I am working on another alternative using https://github.com/seleniumbase/SeleniumBase which gives way more control, but I am still figuring out all its kinks

**Comment by calibrain** [comment]
I just merged a change that should fix the issue (auto kill after 5min of inactivity)Could you try again ?

**Comment by Altycoder** [comment]
Seems to be erroring out now and not working at all, just spun up a new container this morning and tried to download a book

[_calibre-web-automated-book-downloader_logs (1).txt](https://github.com/user-attachments/files/19753906/_calibre-web-automated-book-downloader_logs.1.txt)

**Comment by calibrain** [comment]
Weird, could you share your docker compose with me again ?
And can you make sure docker is using the latest image ?  (`docker pull ghcr.io/calibrain/calibre-web-automated-book-downloader:latest`)

Sorry about this and thank you !

**Comment by Altycoder** [comment]
No worries, my compose is still the same as the first post in this thread

**Comment by calibrain** [comment]
Hum, this is weird, I can't seem to reproduce the error, could you share the full log with me ? Here, or email `calibraindev@gmail.com` or discord `calibrain`

Also, I updated a bunch of stuff in the docker-compose over time, can you update yours ? Take a look at  https://github.com/calibrain/calibre-web-automated-book-downloader/blob/main/docker-compose.yml for the latest

For the debug logs, could you also add these flags :
```
LOG_LEVEL: debug
FLASK_DEBUG: true
APP_ENV: dev
```

(you can mount the log folder for ease of access, its in `/var/log/cwa-book-downloader` by default)

**Comment by Altycoder** [comment]
I added those environment variables then created a new container and searched for and set to download a copy of The Hobbit which was only 0.8MB but it sat there for ages and there are some errors that I could see in the log via portainer but I forgot to mount the directory.  I also searched for a much larger book (which I did earlier) at 83.9MB but that just remained queued. 

I tried again with the directory mounted and went for the larger book first and it eventually gave the same exception, logs below:

[cwa-bookd-downloader.log](https://github.com/user-attachments/files/19759352/cwa-bookd-downloader.log)

[chrome_browser.log](https://github.com/user-attachments/files/19759353/chrome_browser.log)

**Comment by calibrain** [comment]
Do you have some kind of CPU / Memory limitation imposed on the docker ? Is it an ARM host ?
What does your docker stats look like after starting the container but before trying to download a book ? And then after starting a book download ?
Also, what is the host ? Linux ? Is it Unraid or just some plain linux ?
I just pushed #135 to add more logging, could you repull latest and rerun the logs ?
thank you and sorry about the back and forth

I see in the logs that chromium might be crashing, but no idea why

**Comment by Altycoder** [comment]
Hi, I've run out of time today so can do more tomorrow, but for now it's an Arch Linux host running LTS kernel with an x86_64 i5 processor and 32GB RAM.  I'm not imposing any resource limits on the container.

I'll respond to your other questions in the morning if that's ok.

**Comment by calibrain** [comment]
Sure no worries take your time ! And thank you for the details

**Comment by Altycoder** [comment]
Fresh pull, same thing happened unfortunately:

[chrome_browser.log](https://github.com/user-attachments/files/19772165/chrome_browser.log)
[cwa-bd_entrypoint.log](https://github.com/user-attachments/files/19772166/cwa-bd_entrypoint.log)
[cwa-bookd-downloader.log](https://github.com/user-attachments/files/19772164/cwa-bookd-downloader.log)

**Comment by Altycoder** [comment]
(I should also let you know that I reported high idle CPU usage and a memory leak with cloudflarebypassforscraping here: https://github.com/sarperavci/CloudflareBypassForScraping/issues/88)

**Comment by l1berate** [comment]
Hey there @Altycoder I tried to replicate your issue and I can see the high usage from the `CloudflareBypassForScraping` container. If you pull the latest docker image (which should fix any memory/cpu usage issues for the `calibre-web-automated-book-downloader` container), and change your docker compose to not use their container then you should see 0% idle CPU usage and about 150-450 MB of memory usage. I've tried to write out to the best of my ability below how your `docker-compose.yml` would end up looking. 
```
services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: calibre-web-automated-book-downloader
    environment:
      FLASK_PORT: 8095
      FLASK_DEBUG: false
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      UID: ${PUID}
      GID: ${PGID}
      TZ: ${TZ}
      UMASK: 002
    networks:
      - media
    ports:
      - 8095:8095
    restart: unless-stopped
    volumes:
      - ${DOCKER_DIR}/calibre-web-automated/ingest:${INGEST_DIR:-/cwa-book-ingest}
networks:
  media:
    name: omv1
    external: true
```
So in summary, I'd try running the following commands:
```
cd wherever/your/docker/compose/file/is
sudo docker compose down
nano docker-compose.yml # Update yours to stop using the ghcr.io/sarperavci/cloudflarebypassforscraping:latest image
sudo docker pull ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
sudo docker compose up -d

```
Please let me know if you're still facing any issues after that! Thanks.

**Comment by calibrain** [comment]
@l1berate is right !

@Altycoder  we dropped the need to run the CloudflareBypassForScraping since it had high CPU / memory usage and was not compatible with ARM. Now its integrated inside the calibre-web-automated-book-downloader

You should also remove the env `CLOUDFLARE_PROXY_URL` and generally update to the latest docker compose from https://github.com/calibrain/calibre-web-automated-book-downloader/blob/main/docker-compose.yml

**Comment by Altycoder** [comment]
OK I'm back.  I have followed your advice and removed the cloudflarebypassforscraping container, updated my compose file as advised and pulled the new image.  However the container is still broken.

When I start the new container, it sits at ~70MB memory and 1% CPU before I visit the GUI.  When I visit the GUI it remains stable: good so far.

I search for a book and the memory and CPU shoot up to 400MB and 40%.  I then download a book and the memory stays the same and the CPU peaks at 80% CPU then drops to 40% during download, then sits at 15% when back at idle.

So at idle after a book has been downloaded this container is still using 15% CPU and 400MB memory.  I realise the latter may be due to how linux claims and releases memory (potentially) but the CPU usage is a big problem.

Edit, just noticed that a few min after downloading is complete, the CPU is down to 0-1% and memory to ~175MB so there must be something doing that?

What I didn't check before killing the container is that the GUI remains live and another book can be downloaded after the CPU and memory have been controlled.

Log:

[calibre-web.log](https://github.com/user-attachments/files/19862255/calibre-web.log)

**Comment by calibrain** [comment]
So all of this is normal
Basically when you start a download, it will start an X server and Chromium browser
The high CPU is when running all of that and downloading, chromium will eat the CPU
Then once the download finishes, chromium stays idle
After 5min of idle, we automatically kill the chromium server to reclaim memory
(the idea is if you are downloading multiple books one after the other, we don't need to restart chrome server every time, which is heavy)
